services:
  front: 
    container_name: front
    image:  ghcr.io/maelbizot/tp-final-devops-front:latest
    ports:
      - "8080:80"
    depends_on:
      - back
  back:
    container_name: back
    image:  ghcr.io/maelbizot/tp-final-devops-back:latest
    ports:
      - "3000:3000"